//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R3MUS.Devpack.CourierContractNotifier.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("R3MUS.Devpack.CourierContractNotifier.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract has {0} isk collateral set.
        /// </summary>
        public static string CollateralSet {
            get {
                return ResourceManager.GetString("CollateralSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment is incorrect.
        /// </summary>
        public static string IncorrectPayment {
            get {
                return ResourceManager.GetString("IncorrectPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume exceeds maximum volume of {0} m3.
        /// </summary>
        public static string IncorrectSize {
            get {
                return ResourceManager.GetString("IncorrectSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistics Contract {0} at {1}.
        /// </summary>
        public static string MessageFormatLine1 {
            get {
                return ResourceManager.GetString("MessageFormatLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistics Contract {0}.
        /// </summary>
        public static string MessageFormatLine1a {
            get {
                return ResourceManager.GetString("MessageFormatLine1a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer: {0}.
        /// </summary>
        public static string MessageFormatLine2 {
            get {
                return ResourceManager.GetString("MessageFormatLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward: {0} isk.
        /// </summary>
        public static string MessageFormatLine3 {
            get {
                return ResourceManager.GetString("MessageFormatLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume: {0} m3.
        /// </summary>
        public static string MessageFormatLine4 {
            get {
                return ResourceManager.GetString("MessageFormatLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin: {0}.
        /// </summary>
        public static string MessageFormatLine5 {
            get {
                return ResourceManager.GetString("MessageFormatLine5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination: {0}.
        /// </summary>
        public static string MessageFormatLine6 {
            get {
                return ResourceManager.GetString("MessageFormatLine6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct Reward: {0} isk.
        /// </summary>
        public static string MessageFormatLine7 {
            get {
                return ResourceManager.GetString("MessageFormatLine7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://evemaps.dotlan.net/system/{0}.
        /// </summary>
        public static string SystemUrl {
            get {
                return ResourceManager.GetString("SystemUrl", resourceCulture);
            }
        }
    }
}
